# Generated by Django 2.0.4 on 2018-06-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioneer_username', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('session_id', models.CharField(max_length=1000)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_logs', to='livestream.Session'),
        ),
    ]
