# Generated by Django 2.0.4 on 2018-06-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='auction_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
