# Generated by Django 2.0.4 on 2018-06-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180602_0841'),
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='session',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_products', to='profiles.Product'),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
