# Generated by Django 2.0.4 on 2018-06-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='auctioneer_username',
        ),
    ]
