# Generated by Django 2.0.4 on 2018-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
