# Generated by Django 2.0.4 on 2018-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='session',
        ),
        migrations.AddField(
            model_name='logs',
            name='auction_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
