# Generated by Django 2.0.4 on 2018-06-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='products',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='auctioneer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
