# Generated by Django 2.0.4 on 2018-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='auctioneer',
        ),
        migrations.AddField(
            model_name='session',
            name='auctioneer_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
