# Generated by Django 2.0.4 on 2018-06-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_auto_20180608_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='auction_id',
            field=models.IntegerField(default=0),
        ),
    ]
