# Generated by Django 2.0.4 on 2018-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_remove_session_auctioneer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auctioneer_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
