# Generated by Django 2.0.4 on 2018-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_session_auctioneer_username'),
        ('livestream', '0002_auto_20180609_0736'),
    ]

    operations = [
    ]
