# Generated by Django 2.0.4 on 2018-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_sold',
            field=models.DateTimeField(null=True),
        ),
    ]
