# Generated by Django 2.0.4 on 2018-06-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_records',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
