# Generated by Django 2.0.4 on 2018-06-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
        migrations.AddField(
            model_name='credit',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_profile', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.IntegerField(default=0),
        ),
    ]
