# Generated by Django 2.0.4 on 2018-06-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_product_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='product_records',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='records',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
