# Generated by Django 2.0.4 on 2018-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180604_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winning_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
