# Generated by Django 2.0.4 on 2018-05-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180516_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file_name',
        ),
    ]
