# Generated by Django 2.0.4 on 2018-06-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180604_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
        migrations.AddField(
            model_name='credit',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_profile', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='profiles.Bid'),
        ),
    ]
