# Generated by Django 2.0.4 on 2018-06-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile',
        ),
    ]
