# Generated by Django 2.0.4 on 2018-06-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180604_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='profiles.Bid'),
        ),
    ]
