# Generated by Django 2.0.4 on 2018-06-12 02:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_product_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
