# Generated by Django 2.0.4 on 2018-06-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_auto_20180606_0911'),
        ('profiles', '0005_auto_20180604_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_products', to='livestream.Session'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='livestream.Session'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.Profile'),
        ),
    ]
