# Generated by Django 2.0.4 on 2018-06-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='profile',
            field=models.ManyToManyField(related_name='tags', to='profiles.Profile'),
        ),
    ]
