# Generated by Django 2.0.4 on 2018-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180606_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='profile',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
